<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Advertisement_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get advertisement by id
     */
    function get_advertisement($id)
    {
        return $this->db->get_where('advertisement',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all advertisement
     */
    function get_all_advertisement()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('advertisement')->result_array();
    }
        
    /*
     * function to add new advertisement
     */
    function add_advertisement($params)
    {
        $this->db->insert('advertisement',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update advertisement
     */
    function update_advertisement($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('advertisement',$params);
    }
    
    /*
     * function to delete advertisement
     */
    function delete_advertisement($id)
    {
        return $this->db->delete('advertisement',array('id'=>$id));
    }
}
