<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Audio_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('directory');
    }
    
    /*
     * Get Audio by id
     */
    function get_Audio($id)
    {
        return in_array($id, directory_map('asterisk/uploads/dialog'));
    }
    
    
    /*
     * Get Audio by id
     */
    function is_valid($id)
    {
        return in_array($id, directory_map('asterisk/uploads/dialog'));
    }
    
//     /*
//      * Get all Audio count
//      */
//     function get_all_Audio_count()
//     {
//         $this->db->from('Audio');
//         return $this->db->count_all_results();
//     }
        
    /*
     * Get all Audio
     */
    function get_all_Audio($params = array())
    {
        return directory_map('asterisk/uploads/dialog');
    }
        
    /*
     * function to add new Audio
     */
    function add_Audio($params)
    {
        $this->db->insert('Audio',$params);
        return $this->db->insert_id();
    }
 
    
    /*
     * function to delete Audio
     */
    function delete_Audio($id)
    {
        $path_to_file = 'asterisk/uploads/dialog/' . $id;
        if(unlink($path_to_file)) {
           return true;
        }
        else {
           return false;
        }
    }
}
