<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Call_center_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get call_center by id
     */
    function get_call_center($id)
    {
        return $this->db->get_where('call_center',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all call_center
     */
    function get_all_call_center()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('call_center')->result_array();
    }
        
    /*
     * function to add new call_center
     */
    function add_call_center($params)
    {
        $this->db->insert('call_center',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update call_center
     */
    function update_call_center($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('call_center',$params);
    }
    
    /*
     * function to delete call_center
     */
    function delete_call_center($id)
    {
        return $this->db->delete('call_center',array('id'=>$id));
    }
}
