<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Call_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get call by id
     */
    function get_call($id)
    {
        return $this->db->get_where('call',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all call count
     */
    function get_all_call_count()
    {
        $this->db->from('call');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all call
     */
    function get_all_call($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('call')->result_array();
    }
        
    /*
     * function to add new call
     */
    function add_call($params)
    {
        $this->db->insert('call',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update call
     */
    function update_call($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('call',$params);
    }
    
    /*
     * function to delete call
     */
    function delete_call($id)
    {
        return $this->db->delete('call',array('id'=>$id));
    }
}
