<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dnid_has_script_in_schedule_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dnid_has_script_in_schedule by id
     */
    function get_dnid_has_script_in_schedule($id)
    {
        return $this->db->get_where('dnid_has_script_in_schedule',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all dnid_has_script_in_schedule count
     */
    function get_all_dnid_has_script_in_schedule_count()
    {
        $this->db->from('dnid_has_script_in_schedule');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all dnid_has_script_in_schedule
     */
    function get_all_dnid_has_script_in_schedule($params = array())
    {
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->select('*, dnid.id as dId, script_schedule.id as ssId, script.id as sId , dnid_has_script_in_schedule.id as dssId'); //Active query bugs. Overwrite same fields name
        $this->db->from('dnid_has_script_in_schedule');
        $this->db->join('dnid', 'dnid.id = dnid_has_script_in_schedule.dnidId');
        $this->db->join('script', 'script.id = dnid_has_script_in_schedule.scriptId');
        $this->db->join('script_schedule', 'script_schedule.id = dnid_has_script_in_schedule.scriptScheduleId');
        $this->db->order_by('dnid.id', 'ASC');
        return $this->db->get('')->result_array();
    }
        
    /*
     * function to add new dnid_has_script_in_schedule
     */
    function add_dnid_has_script_in_schedule($params)
    {
        $this->db->insert('dnid_has_script_in_schedule',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dnid_has_script_in_schedule
     */
    function update_dnid_has_script_in_schedule($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('dnid_has_script_in_schedule',$params);
    }
    
    /*
     * function to delete dnid_has_script_in_schedule
     */
    function delete_dnid_has_script_in_schedule($id)
    {
        return $this->db->delete('dnid_has_script_in_schedule',array('id'=>$id));
    }
}
