<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Follow_up_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get follow_up by id
     */
    function get_follow_up($id)
    {
        return $this->db->get_where('follow_up',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all follow_up
     */
    function get_all_follow_up()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('follow_up')->result_array();
    }
        
    /*
     * function to add new follow_up
     */
    function add_follow_up($params)
    {
        $this->db->insert('follow_up',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update follow_up
     */
    function update_follow_up($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('follow_up',$params);
    }
    
    /*
     * function to delete follow_up
     */
    function delete_follow_up($id)
    {
        return $this->db->delete('follow_up',array('id'=>$id));
    }
}
