<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lead_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lead by id
     */
    function get_lead($id)
    {
        return $this->db->get_where('lead',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all lead
     */
    function get_all_lead()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('lead')->result_array();
    }
        
    /*
     * function to add new lead
     */
    function add_lead($params)
    {
        $this->db->insert('lead',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lead
     */
    function update_lead($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('lead',$params);
    }
    
    /*
     * function to delete lead
     */
    function delete_lead($id)
    {
        return $this->db->delete('lead',array('id'=>$id));
    }
}
