<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Operator_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get operator_type by id
     */
    function get_operator_type($id)
    {
        return $this->db->get_where('operator_type',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all operator_type
     */
    function get_all_operator_type()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('operator_type')->result_array();
    }
        
    /*
     * function to add new operator_type
     */
    function add_operator_type($params)
    {
        $this->db->insert('operator_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update operator_type
     */
    function update_operator_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('operator_type',$params);
    }
    
    /*
     * function to delete operator_type
     */
    function delete_operator_type($id)
    {
        return $this->db->delete('operator_type',array('id'=>$id));
    }
}
