<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Script_schedule_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get script_schedule by id
     */
    function get_script_schedule($id)
    {
        return $this->db->get_where('script_schedule',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all script_schedule
     */
    function get_all_script_schedule()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('script_schedule')->result_array();
    }
        
    /*
     * function to add new script_schedule
     */
    function add_script_schedule($params)
    {
        $this->db->insert('script_schedule',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update script_schedule
     */
    function update_script_schedule($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('script_schedule',$params);
    }
    
    /*
     * function to delete script_schedule
     */
    function delete_script_schedule($id)
    {
        return $this->db->delete('script_schedule',array('id'=>$id));
    }
}
