<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Security_question_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get security_question_log by id
     */
    function get_security_question_log($id)
    {
        return $this->db->get_where('security_question_log',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all security_question_log
     */
    function get_all_security_question_log()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('security_question_log')->result_array();
    }
        
    /*
     * function to add new security_question_log
     */
    function add_security_question_log($params)
    {
        $this->db->insert('security_question_log',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update security_question_log
     */
    function update_security_question_log($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('security_question_log',$params);
    }
    
    /*
     * function to delete security_question_log
     */
    function delete_security_question_log($id)
    {
        return $this->db->delete('security_question_log',array('id'=>$id));
    }
}
