<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Site_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get site by id
     */
    function get_user($param)
    {
        $db = $this->load->database('fpbx', TRUE);
        return  $db->get_where('ampusers',array('username'=>$param['username']))->row_array();
    }
    
  
}
