<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Spot_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get spot by id
     */
    function get_spot($id)
    {
        return $this->db->get_where('spot',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all spot
     */
    function get_all_spot()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('spot')->result_array();
    }
        
    /*
     * function to add new spot
     */
    function add_spot($params)
    {
        $this->db->insert('spot',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update spot
     */
    function update_spot($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('spot',$params);
    }
    
    /*
     * function to delete spot
     */
    function delete_spot($id)
    {
        return $this->db->delete('spot',array('id'=>$id));
    }
}
